"""init_tables

Revision ID: ebc506150457
Revises:
Create Date: 2026-02-10 15:16:40.343174

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "ebc506150457"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("tool_id", table_name="tools")
    op.drop_table("tools")
    op.drop_index("tool_id", table_name="tools_schema_tmp")
    op.drop_table("tools_schema_tmp")
    op.drop_index("unique_tool_version", table_name="tools_schema_opensource")
    op.drop_table("tools_schema_opensource")
    op.alter_column(
        "tools_schema",
        "app_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="Application ID",
        existing_comment="应用id",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "tool_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="Tool ID",
        existing_comment="工具ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "name",
        existing_type=mysql.VARCHAR(length=128),
        comment="Tool name",
        existing_comment="工具名称",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        comment="Tool description",
        existing_comment="工具描述",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "open_api_schema",
        existing_type=mysql.TEXT(),
        comment="OpenAPI schema, JSON format",
        existing_comment="open api schema，json格式",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema", "create_at", existing_type=mysql.DATETIME(), nullable=True
    )
    op.alter_column(
        "tools_schema",
        "mcp_server_url",
        existing_type=mysql.VARCHAR(length=255),
        server_default=None,
        comment="mcp_server_url",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "schema",
        existing_type=mysql.TEXT(),
        comment="Schema, JSON format",
        existing_comment="schema,json格式",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "version",
        existing_type=mysql.VARCHAR(length=32),
        server_default=None,
        comment="Version number",
        existing_nullable=False,
    )
    op.alter_column(
        "tools_schema",
        "is_deleted",
        existing_type=mysql.BIGINT(display_width=20),
        server_default=None,
        comment="Is deleted",
        existing_nullable=False,
    )
    op.drop_index("unique_tool_version", table_name="tools_schema")
    op.create_unique_constraint(None, "tools_schema", ["tool_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("", "tools_schema", type_="unique")
    op.create_index(
        "unique_tool_version",
        "tools_schema",
        ["tool_id", "version", "is_deleted"],
        unique=True,
    )
    op.alter_column(
        "tools_schema",
        "is_deleted",
        existing_type=mysql.BIGINT(display_width=20),
        server_default=sa.text("'0'"),
        comment=None,
        existing_comment="Is deleted",
        existing_nullable=False,
    )
    op.alter_column(
        "tools_schema",
        "version",
        existing_type=mysql.VARCHAR(length=32),
        server_default=sa.text("'V1.0'"),
        comment=None,
        existing_comment="Version number",
        existing_nullable=False,
    )
    op.alter_column(
        "tools_schema",
        "schema",
        existing_type=mysql.TEXT(),
        comment="schema,json格式",
        existing_comment="Schema, JSON format",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "mcp_server_url",
        existing_type=mysql.VARCHAR(length=255),
        server_default=sa.text("''"),
        comment=None,
        existing_comment="mcp_server_url",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema", "create_at", existing_type=mysql.DATETIME(), nullable=False
    )
    op.alter_column(
        "tools_schema",
        "open_api_schema",
        existing_type=mysql.TEXT(),
        comment="open api schema，json格式",
        existing_comment="OpenAPI schema, JSON format",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        comment="工具描述",
        existing_comment="Tool description",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "name",
        existing_type=mysql.VARCHAR(length=128),
        comment="工具名称",
        existing_comment="Tool name",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "tool_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="工具ID",
        existing_comment="Tool ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "app_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="应用id",
        existing_comment="Application ID",
        existing_nullable=True,
    )
    op.create_table(
        "tools_schema_opensource",
        sa.Column(
            "id",
            mysql.BIGINT(display_width=20),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column("app_id", mysql.VARCHAR(length=32), nullable=True, comment="应用ID"),
        sa.Column("tool_id", mysql.VARCHAR(length=32), nullable=True, comment="工具ID"),
        sa.Column("name", mysql.VARCHAR(length=128), nullable=True, comment="工具名称"),
        sa.Column(
            "description", mysql.VARCHAR(length=512), nullable=True, comment="工具描述"
        ),
        sa.Column(
            "open_api_schema",
            mysql.TEXT(),
            nullable=True,
            comment="open api schema，json格式",
        ),
        sa.Column(
            "create_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "update_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text(
                "CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"
            ),
            nullable=True,
            comment="更新时间",
        ),
        sa.Column(
            "mcp_server_url",
            mysql.VARCHAR(length=255),
            nullable=True,
            comment="mcp_server_url",
        ),
        sa.Column("schema", mysql.TEXT(), nullable=True, comment="schema,json格式"),
        sa.Column(
            "version",
            mysql.VARCHAR(length=32),
            server_default=sa.text("'DEF_VER'"),
            nullable=False,
            comment="版本号",
        ),
        sa.Column(
            "is_deleted",
            mysql.BIGINT(display_width=20),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="是否已删除",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="工具数据库表",
        mysql_comment="工具数据库表",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "unique_tool_version",
        "tools_schema_opensource",
        ["tool_id", "version", "is_deleted"],
        unique=True,
    )
    op.create_table(
        "tools_schema_tmp",
        sa.Column(
            "id", mysql.BIGINT(display_width=20), autoincrement=True, nullable=False
        ),
        sa.Column("app_id", mysql.VARCHAR(length=32), nullable=True, comment="应用id"),
        sa.Column("tool_id", mysql.VARCHAR(length=32), nullable=True, comment="工具ID"),
        sa.Column("name", mysql.VARCHAR(length=128), nullable=True, comment="工具名称"),
        sa.Column(
            "description", mysql.VARCHAR(length=512), nullable=True, comment="工具描述"
        ),
        sa.Column(
            "open_api_schema",
            mysql.TEXT(),
            nullable=True,
            comment="open api schema，json格式",
        ),
        sa.Column(
            "create_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index("tool_id", "tools_schema_tmp", ["tool_id"], unique=True)
    op.create_table(
        "tools",
        sa.Column(
            "id", mysql.BIGINT(display_width=20), autoincrement=True, nullable=False
        ),
        sa.Column("app_id", mysql.VARCHAR(length=32), nullable=True, comment="应用id"),
        sa.Column("tool_id", mysql.VARCHAR(length=32), nullable=True, comment="工具ID"),
        sa.Column("name", mysql.VARCHAR(length=128), nullable=True, comment="工具名称"),
        sa.Column(
            "description", mysql.VARCHAR(length=512), nullable=True, comment="工具描述"
        ),
        sa.Column(
            "open_api_schema",
            mysql.TEXT(),
            nullable=True,
            comment="open api schema，json格式",
        ),
        sa.Column("create_at", mysql.DATETIME(), nullable=False),
        sa.Column("update_at", mysql.DATETIME(), nullable=False),
        sa.Column("mcp_server_url", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("schema", mysql.TEXT(), nullable=True, comment="schema,json格式"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index("tool_id", "tools", ["tool_id"], unique=True)
    # ### end Alembic commands ###
